env:
  global:
    - CC_TEST_REPORTER_ID=9a87b9735c0709a65cb1353b8865776cf2dfbc8e2963a34a0ec583b1438afb7c
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
language: ruby
rvm:
  - 2.5.0
  - 2.4.3
  - 2.4.0
  - 2.3.0
  - 2.2.0
  - 2.1
  - 2.0.0
before_install: gem install bundler
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
